[[pages]]
name = "è¯´æ˜"
icon = "ğŸ“–"
is_section = true

[[pages]]
name = "è½¯ä»¶è¯´æ˜"
icon = "ğŸ“–"
path = "pages/description/software_description.py"

[[pages]]
name = "å¼€å‘æŒ‡å—"
icon = "ğŸ“–"
path = "pages/description/dev_guide.py"

[[pages]]
name = "st-pagesä½¿ç”¨æŒ‡å—"
icon = "ğŸ“–"
path = "pages/description/st_pages_guide.py"

[[pages]]
name = "Excelå·¥å…·"
icon = "ğŸ“Š"
is_section = true

[[pages]]
name = "XLSè½¬XLSXå·¥å…·"
icon = "ğŸ“Š"
path = "pages/excel_tools/xls_to_xlsx.py"

[[pages]]
name = "Excel-Sheetæ‹†åˆ†"
icon = "ğŸ“Š"
path = "pages/excel_tools/excel_sheet_splitter.py"

[[pages]]
name = "Excelæ ‡é¢˜ä¸è¡¨å¤´æ¸…æ´—"
icon = "ğŸ“Š"
path = "pages/excel_tools/excel_title_cleaner.py"

[[pages]]
name = "Wordå·¥å…·"
icon = "ğŸ“„"
is_section = true

[[pages]]
name = "DOCè½¬DOCXå·¥å…·"
icon = "ğŸ“„"
path = "pages/word_tools/word_to_docx.py"

[[pages]]
name = "Wordè½¬PDFå·¥å…·"
icon = "ğŸ“„"
path = "pages/word_tools/word_to_pdf.py"

[[pages]]
name = "DOCXé¡µçœ‰ã€é¡µè„šæ¸…ç†"
icon = "ğŸ§¹"
path = "pages/word_tools/word_clean.py"

[[pages]]
name = "PDFå·¥å…·"
icon = "ğŸ“‹"
is_section = true

[[pages]]
name = "PDFè½¬Markdownå·¥å…·"
icon = "ğŸ“‹"
path = "pages/pdf_tools/pdf_to_markdown.py"